In [1]:
import sys 
# setting path
sys.path.append('../')

In [2]:
%load_ext autoreload
%autoreload 2

In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

### Processing COVID Data

In [6]:
df = pd.read_csv('./data/20220319_covid_merge.csv', sep=",")
df = df.rename(columns={"new_deaths_per_million": 'y'})

In [7]:
columns=df.columns
for f in df.columns:
    if df[f].dtype == 'object':
        df[f] = LabelEncoder().fit_transform(list(df[f]))

In [8]:
df.head()

,location,new_cases_per_million,y,population_cov,life_expectancy_cov,Population,Area_km2,Density_km2,Year_x,Meningitis,...,Cardiovascular diseases,Chronic kidney disease,Chronic respiratory diseases,Cirrhosis and other chronic liver diseases,Digestive diseases,Acute hepatitis,Alzheimer's disease and other dementias,Parkinson's disease,Total,air_polution
0,0,4171.944,186.538,39835428.0,64.83,37171921.0,252071.0,57.0,2019.0,0.004205,...,0.166779,0.015165,0.019052,0.010215,0.018640,0.005219,0.004775,0.001507,0.585498,52.99812
1,1,92109.327,1176.434,2872934.0,78.57,2882740.0,11100.0,100.0,2019.0,0.000451,...,0.447630,0.011413,0.028272,0.011552,0.018281,0.000035,0.031810,0.008603,0.771315,18.45981
2,2,5782.052,148.940,44616626.0,76.88,42228408.0,919590.0,18.0,2019.0,0.000691,...,0.231908,0.019421,0.017827,0.009579,0.015151,0.000613,0.012335,0.003038,0.455347,32.91557
3,3,473136.492,1900.384,77354.0,83.73,77006.0,181.0,165.0,2019.0,0.000000,...,0.219463,0.020778,0.050645,0.015583,0.035062,0.001299,0.046750,0.009090,0.762278,9.51265
4,4,2898.709,55.799,33933611.0,61.15,30809787.0,481351.0,25.0,2019.0,0.008179,...,0.083493,0.007997,0.012769,0.018390,0.029117,0.000798,0.003710,0.000867,0.562613,28.02152

In [10]:
df.to_csv('./data/20220319_covid_merge_processed.csv', sep=";", index=False)