In [1]:
import sys; sys.path.insert(0, '../..') # add parent folder path where lib folder is

%load_ext autoreload
%autoreload 2

import pandas as pd
pd.set_option('display.max_rows', 700)


from pathlib import Path
import numpy as np

In [2]:
path = '/mnt/c/Users/rwmas/GitHub/xai/python-asd-copy/xai/test/rs_knockoffs_tokamat/'

files = Path(path).glob('*.csv')  

dfs = list()
for f in files:
    data = pd.read_csv(f, sep=';')
    # .stem is method for pathlib objects to get the filename w/o the extension
    data['file'] = f.stem
    dfs.append(data)

df = pd.concat(dfs, ignore_index=True)

In [3]:
### We have done 69 tests on the covid dataset, each test with 20,000 iterations.
### This notebooks compares the results of each iteration to see if the ranks differe among various iterations or not.
### To varify that, we took combine all the files and took the mean rank of each column and divide it by the max rank of that column among all the files/test. The highest rank
### /relevance of a col in each test is 40 since there are 40 number of columns in covid dataset. The rank number than descend all the way to 0 where 0 indicates no 
# contribution/relevance at all. The idea is that if the mean of a column will give us the mean rank of the respective variable, i.e., a mean of 40 will show that this column
# was always ranked in 40 in all the files/tests but if a column would have ranked 39 in even one test but 40 in all other rests, its mean would be less than 40. 
# Now if we divide this mean with the max rank we will be able to identify columns where the rank was varied among the 69 test. I.e., mean_rank / max_rank < 1.

In [4]:
df_max_ranks = df.groupby(['cols'])['0'].max()
df_mean_ranks = df.groupby(['cols'])['0'].mean()

In [5]:
df_final = pd.merge(df_max_ranks, df_mean_ranks, on='cols').reset_index()
df_final.columns = ['cols', 'max_ranked', 'mean_ranked']

In [6]:
df_final = df_final.sort_values(by=['mean_ranked'], ascending=False)
df_final

        cols  max_ranked  mean_ranked
19    ICFREQ        64.0         64.0
4     BGASA2        63.0         63.0
2    AUXHEAT        62.0         62.0
6     BGASZ2        61.0         61.0
18    ICFORM        60.0         60.0
32    PECRHC        59.0         59.0
21    INDENT        58.0         58.0
50    TAUC92        57.0         57.0
62     XGASZ        56.0         56.0
17   ICANTEN        55.0         55.0
35     PGASA        54.0         54.0
31     PECRH        53.0         53.0
51    TAUC93        52.0         52.0
36     PGASZ        51.0         51.0
3      BGASA        50.0         50.0
39    PICRHC        49.0         49.0
29   NELFORM        48.0         48.0
14    DNELDT        47.0         47.0
55   TIME_ID         0.0          0.0
46      RGEO         0.0          0.0
60    WFFORM         0.0          0.0
41     PINJ2         0.0          0.0
42        PL         0.0          0.0
43      PNBI         0.0          0.0
59    WALMAT         0.0          0.0
44      POHM         0.0          0.0
45       Q95         0.0          0.0
48      SHOT         0.0          0.0
47    SEPLIM         0.0          0.0
49  SURFFORM         0.0          0.0
58     VSURF         0.0          0.0
61     XGASA         0.0          0.0
57       VOL         0.0          0.0
52     TAUTH         0.0          0.0
56       TOK         0.0          0.0
53    TAUTOT         0.0          0.0
54      TIME         0.0          0.0
40      PINJ         0.0          0.0
0       AMIN         0.0          0.0
38     PICRH         0.0          0.0
20  ICSCHEME         0.0          0.0
5      BGASZ         0.0          0.0
7    BSOURCE         0.0          0.0
8   BSOURCE2         0.0          0.0
9         BT         0.0          0.0
10    CONFIG         0.0          0.0
11     DELTA         0.0          0.0
12    DIVMAT         0.0          0.0
13   DIVNAME         0.0          0.0
15      DWHC         0.0          0.0
16      EVAP         0.0          0.0
22        IP         0.0          0.0
37     PHASE         0.0          0.0
23      ISEQ         0.0          0.0
24     KAPPA         0.0          0.0
25    KAPPAA         0.0          0.0
26     KAREA         0.0          0.0
27    LIMMAT         0.0          0.0
28      MEFF         0.0          0.0
30    PALPHA         0.0          0.0
1       AREA         0.0          0.0
33    PELLET         0.0          0.0
34    PFLOSS         0.0          0.0
63     index         0.0          0.0

In [7]:
df_final.head(70)

        cols  max_ranked  mean_ranked
19    ICFREQ        64.0         64.0
4     BGASA2        63.0         63.0
2    AUXHEAT        62.0         62.0
6     BGASZ2        61.0         61.0
18    ICFORM        60.0         60.0
32    PECRHC        59.0         59.0
21    INDENT        58.0         58.0
50    TAUC92        57.0         57.0
62     XGASZ        56.0         56.0
17   ICANTEN        55.0         55.0
35     PGASA        54.0         54.0
31     PECRH        53.0         53.0
51    TAUC93        52.0         52.0
36     PGASZ        51.0         51.0
3      BGASA        50.0         50.0
39    PICRHC        49.0         49.0
29   NELFORM        48.0         48.0
14    DNELDT        47.0         47.0
55   TIME_ID         0.0          0.0
46      RGEO         0.0          0.0
60    WFFORM         0.0          0.0
41     PINJ2         0.0          0.0
42        PL         0.0          0.0
43      PNBI         0.0          0.0
59    WALMAT         0.0          0.0
44      POHM         0.0          0.0
45       Q95         0.0          0.0
48      SHOT         0.0          0.0
47    SEPLIM         0.0          0.0
49  SURFFORM         0.0          0.0
58     VSURF         0.0          0.0
61     XGASA         0.0          0.0
57       VOL         0.0          0.0
52     TAUTH         0.0          0.0
56       TOK         0.0          0.0
53    TAUTOT         0.0          0.0
54      TIME         0.0          0.0
40      PINJ         0.0          0.0
0       AMIN         0.0          0.0
38     PICRH         0.0          0.0
20  ICSCHEME         0.0          0.0
5      BGASZ         0.0          0.0
7    BSOURCE         0.0          0.0
8   BSOURCE2         0.0          0.0
9         BT         0.0          0.0
10    CONFIG         0.0          0.0
11     DELTA         0.0          0.0
12    DIVMAT         0.0          0.0
13   DIVNAME         0.0          0.0
15      DWHC         0.0          0.0
16      EVAP         0.0          0.0
22        IP         0.0          0.0
37     PHASE         0.0          0.0
23      ISEQ         0.0          0.0
24     KAPPA         0.0          0.0
25    KAPPAA         0.0          0.0
26     KAREA         0.0          0.0
27    LIMMAT         0.0          0.0
28      MEFF         0.0          0.0
30    PALPHA         0.0          0.0
1       AREA         0.0          0.0
33    PELLET         0.0          0.0
34    PFLOSS         0.0          0.0
63     index         0.0          0.0

In [8]:
# since none of the df_final.mean_ranked/df_final.max_ranked values are < 1, this implies that all our knockoff iterations gives the same results. 
# As per the above dataset new_cases_per_million is of highest importance and all those with 0 rank has no relevance at all.
df_final.mean_ranked/df_final.max_ranked

19    1.0
4     1.0
2     1.0
6     1.0
18    1.0
32    1.0
21    1.0
50    1.0
62    1.0
17    1.0
35    1.0
31    1.0
51    1.0
36    1.0
3     1.0
39    1.0
29    1.0
14    1.0
55    NaN
46    NaN
60    NaN
41    NaN
42    NaN
43    NaN
59    NaN
44    NaN
45    NaN
48    NaN
47    NaN
49    NaN
58    NaN
61    NaN
57    NaN
52    NaN
56    NaN
53    NaN
54    NaN
40    NaN
0     NaN
38    NaN
20    NaN
5     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
15    NaN
16    NaN
22    NaN
37    NaN
23    NaN
24    NaN
25    NaN
26    NaN
27    NaN
28    NaN
30    NaN
1     NaN
33    NaN
34    NaN
63    NaN
dtype: float64